"""initial_schema

Revision ID: ae361b14a043
Revises: 
Create Date: 2026-07-12 11:26:00.772047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae361b14a043'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('license_category', sa.String(length=20), nullable=False),
    sa.Column('license_expiry', sa.Date(), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=False),
    sa.Column('trip_completion_pct', sa.Integer(), nullable=False),
    sa.Column('safety_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'ON_TRIP', 'OFF_DUTY', 'SUSPENDED', name='driver_status'), nullable=False),
    sa.CheckConstraint('safety_score >= 0.00 AND safety_score <= 100.00', name='chk_driver_safety_score'),
    sa.CheckConstraint('trip_completion_pct >= 0 AND trip_completion_pct <= 100', name='chk_trip_completion_pct'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_license_number'), 'drivers', ['license_number'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('registration_number', sa.String(length=20), nullable=False),
    sa.Column('name_model', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('capacity_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('odometer', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('acquisition_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'ON_TRIP', 'IN_SHOP', 'RETIRED', name='vehicle_status'), nullable=False),
    sa.CheckConstraint('acquisition_cost >= 0', name='chk_vehicle_acquisition_cost'),
    sa.CheckConstraint('capacity_kg > 0', name='chk_vehicle_capacity'),
    sa.CheckConstraint('odometer >= 0', name='chk_vehicle_odometer'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_registration_number'), 'vehicles', ['registration_number'], unique=True)
    op.create_table('fuel_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('liters', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('odometer', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('cost >= 0', name='chk_fuel_cost'),
    sa.CheckConstraint('liters > 0', name='chk_fuel_liters'),
    sa.CheckConstraint('odometer >= 0', name='chk_fuel_odometer'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('service_type', sa.String(length=100), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', name='maintenance_status'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.CheckConstraint("status != 'COMPLETED' OR end_date IS NOT NULL", name='chk_maint_completion_date'),
    sa.CheckConstraint('cost >= 0', name='chk_maint_cost'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_code', sa.String(length=20), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('dispatcher_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('cargo_weight', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('planned_distance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_distance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dispatch_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completion_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'DISPATCHED', 'COMPLETED', 'CANCELLED', name='trip_status'), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint("status != 'COMPLETED' OR (actual_distance IS NOT NULL AND completion_time IS NOT NULL)", name='chk_trip_completion_data'),
    sa.CheckConstraint('actual_distance IS NULL OR actual_distance >= 0', name='chk_actual_distance'),
    sa.CheckConstraint('cargo_weight > 0', name='chk_trip_cargo'),
    sa.CheckConstraint('planned_distance > 0', name='chk_planned_distance'),
    sa.CheckConstraint('revenue >= 0', name='chk_trip_revenue'),
    sa.ForeignKeyConstraint(['dispatcher_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_driver_active_trip', 'trips', ['driver_id'], unique=True, postgresql_where=sa.text("status = 'DISPATCHED'"))
    op.create_index('idx_vehicle_active_trip', 'trips', ['vehicle_id'], unique=True, postgresql_where=sa.text("status = 'DISPATCHED'"))
    op.create_index(op.f('ix_trips_trip_code'), 'trips', ['trip_code'], unique=True)
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('type', sa.Enum('FUEL', 'MAINTENANCE', 'TOLL', 'PARKING', 'OTHER', name='expense_type'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.CheckConstraint('amount > 0', name='chk_expense_amount'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    op.drop_index(op.f('ix_trips_trip_code'), table_name='trips')
    op.drop_index('idx_vehicle_active_trip', table_name='trips', postgresql_where=sa.text("status = 'DISPATCHED'"))
    op.drop_index('idx_driver_active_trip', table_name='trips', postgresql_where=sa.text("status = 'DISPATCHED'"))
    op.drop_table('trips')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('maintenance_logs')
    op.drop_table('fuel_logs')
    op.drop_index(op.f('ix_vehicles_registration_number'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_drivers_license_number'), table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
